add k8s podcast
cilium/cilium.io pull request #24
Opened 2022-03-07 13:24 UTC by xmulligan

2022-03-07 13:29 UTC, xmulligan commented
/lgtm

2022-03-08 10:16 UTC, liquidat requested changes
Please update image to the larger version which has no compressing artifacts.

2022-03-08 10:16 UTC, liquidat commented on src/posts/2021-01-12-k8s-pocast/index.md
> +ogImageUrl: 'https://pbs.twimg.com/profile_images/1095059886730137600/icMSa8g4_400x400.jpg'
Replace with this image:
https://pbs.twimg.com/profile_images/1095059886730137600/icMSa8g4.jpg

2022-03-09 09:41 UTC, xmulligan commented on src/posts/2021-01-12-k8s-pocast/index.md
> +ogImageUrl: 'https://pbs.twimg.com/profile_images/1095059886730137600/icMSa8g4_400x400.jpg'
```suggestion
ogImageUrl: 'https://pbs.twimg.com/profile_images/1095059886730137600/icMSa8g4.jpg'
```

2022-03-09 09:47 UTC, xmulligan commented
/lgtm

2022-03-09 13:52 UTC, xmulligan commented on src/posts/2021-01-12-k8s-pocast/index.md
> +  - Technology
```suggestion
  - Community
```

2022-03-09 16:23 UTC, liquidat approved these changes

2022-03-09 16:24 UTC, merged