feat: develop events page
cilium/cilium.io pull request #279
Opened 2023-06-01 13:06 UTC by nikvoblikov

**This PR:**
Adds an Events page:
- Updated "Filters" and "Pagination" components for use in "Events" and "Blog";
- Adds links to the footer and menu "News and Media";
- Adds necessary events.

TODO before merge:
- [x]  Delete test events;

**Steps to test**

- Open the [Events page](https://deploy-preview-279--cilium.netlify.app/events/)
- Open the [Blog page](https://deploy-preview-279--cilium.netlify.app/blog/)
- Confirm that everything looks and works as expected

2023-06-15 14:05 UTC, vannyle requested changes

2023-06-15 14:05 UTC, vannyle commented on gatsby-node.js
> +  const initialFilters = getInitialFilters(eventFilters);
```suggestion
  const initialFilters = allFilters.reduce((acc, { label }) => {
    if (!acc[label]) {
      acc[label] = [];
    }
    return acc;
  }, {});
```

2023-06-15 14:05 UTC, vannyle commented on src/utils/event-filters.js
> +}
```suggestion

```

2023-06-15 14:05 UTC, vannyle commented on src/utils/event-filters.js
> +  getInitialFilters,
```suggestion
```

2023-06-15 14:05 UTC, vannyle commented on gatsby-node.js
> +  const initialFilters = getInitialFilters(eventFilters);
IMHO, as it was not a reusable function, it is a shorter way to just get initialFilters here, not importing from utils.

2023-06-16 10:06 UTC, nikvoblikov commented on src/components/pages/events/events-board/event-card/event-card.jsx
> +    <EventCover ogImage={ogImage} title={title} />
This component is in /events/events-board/event-card/ that's why it's called that:)

2023-06-16 10:25 UTC, vannyle commented on src/components/pages/events/events-board/event-card/event-card.jsx
> +const BlogPostCard = ({
The component BlogPostCard?

2023-06-20 11:39 UTC, sashasushko approved these changes
LGTM 🔥 

Only one thing... please hide "[What’s New with Cilium & eBPF South Bay Meetup](https://isovalent.com/whats-new-with-cilium-ebpf-south-bay-meetup/)" because it give 404

2023-06-21 10:57 UTC, xmulligan commented
Great, can we make sure all of the events have thumbnails not just the generic one and can we make this CiliumCon the featured one https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/co-located-events/ciliumcon/ and move the other one down?

2023-06-22 09:53 UTC, xmulligan commented on content/events/2023-04-18-ciliumcon/index.md
> +title: 'CiliumCon'
```suggestion
title: 'CiliumCon EU 2023'
```

2023-06-22 09:53 UTC, xmulligan commented on content/events/2023-11-06-ciliumcon-na/index.md
> +title: 'CiliumCon'
```suggestion
title: 'CiliumCon NA 2023'
```

2023-06-23 06:04 UTC, xmulligan commented
Sorry I wasn't more clear. What I meant is that I wanted the image listing all of the talks as the thumbnail on the events page, not the other way around

2023-06-23 09:56 UTC, nikvoblikov commented
I have changed the pictures. I want to note that for correct display for events, images must be 760x360 pixels in size, so I slightly changed the aspect ratio of the image.

2023-06-23 09:56 UTC, nikvoblikov commented
> Sorry I wasn't more clear. What I meant is that I wanted the image listing all of the talks as the thumbnail on the events page, not the other way around

I have changed the pictures. I want to note that for correct display for events, images must be 760x360 pixels in size, so I slightly changed the aspect ratio of the image.

2023-06-26 14:44 UTC, xmulligan approved these changes

2023-06-26 14:44 UTC, merged