feat: add new pages & update content and design for current pages
cilium/cilium.io pull request #36
Opened 2022-03-14 14:30 UTC by vannyle

**Describe changes**
This pull request brings:
- [Get help](https://deploy-preview-36--cilium.netlify.app/get-help) page
- [Get Involved](https://deploy-preview-36--cilium.netlify.app/get-involved) page
- [Adopters](https://deploy-preview-36--cilium.netlify.app/adopters) page
- [Telling the Cilium story](https://deploy-preview-36--cilium.netlify.app/telling-story) page
- [Newsletter](https://deploy-preview-36--cilium.netlify.app/newsletter) page
- updated [Learn](https://deploy-preview-36--cilium.netlify.app/get-started) page (Get Started now)
- updated [Enterprise](https://deploy-preview-36--cilium.netlify.app/enterprise) page
- updated [Home](https://deploy-preview-36--cilium.netlify.app) page
- updated menu

**Additional changes**
- added a new theme to MainLayout and Community
- enhanced HTML semantic tags in header & footer
- created the reusable components Cards

**Step to steps**
1. Open all pages above.
2. Confirm that everything works as expected.

**TODO**
- [x] add SEO metadata
- [x]  integrate subscribe form
- [x] create submenu that link to new pages
- [ ] add missing URLs

2022-03-14 17:06 UTC, bolotskydev commented on src/components/pages/get-help/cards/cards.jsx
> +  <section className="bg-gray-4 pt-12 pb-28">
I'm afraid we can not use `section` tag here due to absent heading tag as mentioned [here](https://stackoverflow.com/questions/8544671/is-it-necessary-to-have-a-heading-of-section-in-html5), let's switch to div

2022-03-14 17:13 UTC, SilencerWeb requested changes

2022-03-14 17:13 UTC, SilencerWeb commented on src/components/pages/get-help/cards/cards.jsx
> +    PropTypes.shape({
Let's use `exact` instead of `shape` since it's more useful

2022-03-14 17:13 UTC, SilencerWeb commented on src/components/pages/get-help/cards/cards.jsx
> +          <div
Let's use `ul` and `li` here for better semantic

2022-03-14 17:13 UTC, SilencerWeb commented on src/components/pages/get-help/cards/cards.jsx
> +                rel={buttonTarget ? 'noopener noreferrer' : ''}
Also, please check out errors and warnings that HTML validators gives and let's try to fix as much as possible of them — https://validator.w3.org/nu/?doc=https%3A%2F%2Fdeploy-preview-36--cilium.netlify.app%2Fget-help%2F

2022-03-15 11:30 UTC, SilencerWeb approved these changes

2022-04-08 09:33 UTC, xmulligan approved these changes

2022-04-08 09:33 UTC, merged