add cni deep dive part 1 to blog
cilium/cilium.io pull request #59
Opened 2022-04-11 09:15 UTC by xmulligan

2022-04-25 15:07 UTC, liquidat requested changes
I'd add that this covers a video.

2022-04-26 08:40 UTC, xmulligan commented on src/posts/2022-02-23-cni-deep-dive/index.md
> +ogSummary: 'Learn what Cilium is and how it leverages eBPF to provide load balancing, observability, and security'
```suggestion
ogSummary: 'This video covers what Cilium is and how it leverages eBPF to provide load balancing, observability, and security'
```

2022-04-26 09:37 UTC, liquidat approved these changes

2022-04-26 09:38 UTC, liquidat commented
@xmulligan There are build failures, can you please check?

2022-04-26 11:23 UTC, xmulligan commented on src/posts/2022-02-23-cni-deep-dive/index.md
> +ogImageUrl: 'https://heise.cloudimg.io/v7/_www-heise-de_/imgs/18/2/9/5/4/2/1/8/cilium-diagramm-da030a781be5edc2.png?org_if_sml=1&q=70&width=1220'
```suggestion
ogImageUrl: 'https://docs.cilium.io/en/stable/_images/cilium-arch.png'
```

2022-04-26 11:42 UTC, xmulligan commented
@liquidat should be good now

2022-04-28 13:58 UTC, xmulligan commented on src/posts/2022-02-23-cni-deep-dive/index.md
> +ogSummary: 'This video covers what Cilium is and how it leverages eBPF to provide load balancing, observability, and security'
```suggestion
ogSummary: 'This video from The Learning Channel covers what Cilium is and how it leverages eBPF to provide load balancing, observability, and security'
```

2022-04-28 14:03 UTC, merged